name: deploy gh-pages
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and deploy gh-pages
    env:
      MY_SECRET   : ${{secrets.commit_secret}}
      USER_NAME   : InvokFung
      USER_EMAIL  : InvokFung@fake.com
      PUBLISH_DIR : ./dist
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        npm ci
        npm i @rollup/rollup-linux-x64-gnu    
    - name: Build
      run: npm run build  # replace with your build command

    - name: Deploy to GitHub Pages
      uses: actions/gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist